export const ADD_MESSAGE = 'ADD_MESSAGE';

export const SWITCH_ROOM = 'SWITCH_ROOM';

export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_SIGNING_IN = 'AUTH_SIGNING_IN';
export const AUTH_SIGN_IN_FAIL = 'AUTH_SIGN_IN_FAIL';

export const AUTH_VERIFICATION = 'AUTH_VERIFICATION';
export const AUTH_VERIFICATION_FAIL = 'AUTH_VERIFICATION_FAIL';
export const AUTH_VERIFICATION_SUCCESS = 'AUTH_VERIFICATION_SUCCESS';

export const CHANGE_WIDTH = 'CHANGE_WIDTH';
